settings:
  app:
    name:
      type: string
      value: Order Tool Dev
  http:
    port:
      type: int
      value: 8080
  database:
    user:
      type: string
      value: app_dev
    password:
      type: string
      secret: true
      encrypted: true
      value: ENC[AES256_GCM,data:example,type:str]
