package com.example;

public class App {
    public static void main(String[] args) {
        System.out.println("Building Rail...");

        // AppConfigRail should be generated by the annotation processor
        AppConfigRail rail = AppConfigRail.start();

        rail.ctx().input("Hello Railix");

        rail.step(r -> {
            String in = rail.ctx().input();
            System.out.println("Input: " + in);

            // Logic
            int len = in.length();

            rail.ctx().output(len);
        })
                .finish();

        System.out.println("Rail Finished.");

        // Verify output
        // Metadata access might be tricky if I don't reference the instance 'rail'
        // properly inside the step?
        // Actually rail.ctx() methods put/get directly from the underlying meta map.
        // So checking the meta map after execution should work.

        Integer out = rail.ctx().output();
        System.out.println("Output: " + out);

        if (out != 12) { // "Hello Railix".length() == 12
            throw new RuntimeException("Assertion failed: Output expected 12 but got " + out);
        }
    }
}
